[package]
name = "watum-rust"
version = "0.1.0"
authors = ["Mostafa <ramezani.m@ut.ac.ir>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
